import pandas as pd
import matplotlib.pyplot as plt

csv_path = "/content/runs/yolo_fracture_lowmem2/results.csv"
df = pd.read_csv(csv_path)
print("🧾 Các cột trong file:", list(df.columns))
plt.figure(figsize=(10, 5))
plt.plot(df["epoch"], df["train/box_loss"], label="Box Loss")
plt.plot(df["epoch"], df["train/cls_loss"], label="Cls Loss")
plt.plot(df["epoch"], df["train/dfl_loss"], label="DFL Loss")
plt.title("📉 Training Loss theo Epoch")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()
plt.grid(True)
plt.show()
plt.figure(figsize=(10, 5))
plt.plot(df["epoch"], df["metrics/mAP50(B)"], label="mAP@0.5")
plt.plot(df["epoch"], df["metrics/mAP50-95(B)"], label="mAP@0.5:0.95")
plt.title("📈 mAP theo Epoch")
plt.xlabel("Epoch")
plt.ylabel("Giá trị mAP")
plt.legend()
plt.grid(True)
plt.show()
plt.figure(figsize=(10, 5))
plt.plot(df["epoch"], df["metrics/precision(B)"], label="Precision")
plt.plot(df["epoch"], df["metrics/recall(B)"], label="Recall")
plt.title("🎯 Precision và Recall theo Epoch")
plt.xlabel("Epoch")
plt.ylabel("Giá trị")
plt.legend()
plt.grid(True)
plt.show()
